### ISSUE TITLE
Allow order of layers to be changed (be able to bring layers forward / backward)

### ISSUE THREAD

**Issue by markmanx** [markmanx/isoflow#11]
Changing the order of overlapping elements is extremely cumbersome (user has to delete the furthest layer and recreate it to bring it to the top of the stack).  We need an easier way to manipulate ordering (see the scenario below).  The big question is how should the UI look. 

Option 1. We implement a context menu (e.g. a menu that appears when the element is right-clicked, see below), or 
Option 2.  We put the ordering controls in our existing sidebar (and avoid creating a whole new menu mechanic)? 

<img width="963" alt="image" src="https://github.com/markmanx/isoflow/assets/1769678/e8c50724-9663-4c5a-afef-1db100512fc3">

Context menu example:
<img width="259" alt="image" src="https://github.com/markmanx/isoflow/assets/1769678/2965e3ab-c9bf-468c-a309-ab7ef047ee5d">

**Comment by NorseGaud** [comment]
Coming from other tools, the context menu that's in v2 works well and was expected.
