### ISSUE TITLE
What my company needs

### ISSUE THREAD

**Issue by NorseGaud** [markmanx/isoflow#24]
Hey! Love Isoflow and wanted to provide some feedback on what my company needs in order to use Isoflow for all of our architecture diagrams, etc:

1. Ability to group inside of groups (currently possible, but painful due to the lack of bring to front/back)
2. Ability to resize groups. While creating, I often find I need to resize a grouping as I over or under-estimated the size I need. Without bring to front/back for the group, recreation is not possible as I need groups inside of groups.

Once we have those, we'd totally pay for a service/web app allowing us to create these.

**Comment by markmanx** [comment]
Thanks for the feedback.  Coincidentally those features are on the roadmap and are currently being worked on.  They should be live on isoflow.io next week.  Stay tuned!  

https://github.com/markmanx/isoflow/assets/1769678/76b512ab-00d9-463d-8935-178304269c83

**Comment by NorseGaud** [comment]
Wohoo!!!
