### ISSUE TITLE
Docker image

### ISSUE THREAD

**Issue by Icybrew** [markmanx/isoflow#29]
Any plans for releasing docker image?

**Comment by markmanx** [comment]
@Icybrew No plans as yet, although I think it should be relatively straight forward to deploy a Docker image at the same time as when the package gets published to npm via CI.  I can't attach any timelines, but if someone wants to make a PR with a Dockerfile, I can setup the pipeline automation.

**Comment by vacharanon** [comment]
#38 added a Dockerfile as a standalone build. That could close this issue.

**Comment by markmanx** [comment]
Also, we now have an image published to Docker Hub [here](https://hub.docker.com/r/markmanx/isoflow/tags).  Thanks to @vacharanon for this initiative.
