### ISSUE TITLE
Export without grid background

### ISSUE THREAD

**Issue by sakkarose** [markmanx/isoflow#45]
I have tried exploring and didn't find a way to export without the grid so I assumed this isn't implemented yet.
I don't think there is much things to be considered, just the ability to export the current diagram with a white background without grid.

Thank you so much.

**Comment by markmanx** [comment]
Implemented with https://github.com/markmanx/isoflow/pull/36.

**Comment by sakkarose** [comment]
Oh I didn't notice. It's just the version of isoflow.io was a bit behind.
